---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full 
summary: Sie können die Einstellungen für ein gespiegeltes Paar-Volume ändern, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paar-Volumes voll ist. 
---
= Ändern Sie die Einstellungen für die reservierte Kapazität eines gespiegelten Paar-Volumes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für ein gespiegeltes Paar-Volume ändern, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paar-Volumes voll ist.

.Schritte
. Wählen Sie Menü:Speicher[Pools & Volume Groups].
. Wählen Sie die Registerkarte *reservierte Kapazität* aus.
. Wählen Sie das zu bearbeitende gespiegelte Paar-Volume aus und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld *Mirrored Pair Volume Reserved Capacity Settings* wird angezeigt.

. Ändern Sie gegebenenfalls die Einstellungen für die reservierte Kapazität des gespiegelten Paar-Volumes.
+
.Felddetails
[%collapsible]
====
[cols="1a,3a"]
|===
| Einstellung | Beschreibung 


 a| 
Benachrichtigen, wenn...
 a| 
Verwenden Sie das Spinner-Feld, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paares sich der vollen Kapazität nähert.

Wenn die reservierte Kapazität für das gespiegelte Paar den angegebenen Schwellenwert überschreitet, sendet System Manager eine Warnmeldung, sodass Sie die reservierte Kapazität erweitern können.


NOTE: Durch Ändern der Alarmeinstellung für ein gespiegeltes Paar wird die Alarmeinstellung für alle gespiegelten Paare, die zur gleichen SpiegelungsConsistency Group gehören, geändert.



 a| 
Richtlinie für vollständig reservierte Kapazität
 a| 
Sie können eine der folgenden Richtlinien auswählen:

** *Ältestes Snapshot-Image löschen* – System Manager entfernt automatisch das älteste Snapshot-Image in der Consistency Group, das die reservierte Kapazität des Mitglieds zur Wiederverwendung innerhalb der Gruppe freigibt.
** *Schreibvorgänge auf Basis-Volume ablehnen* – Wenn die reservierte Kapazität ihren maximalen festgelegten Prozentsatz erreicht, weist System Manager alle I/O-Schreibanfragen auf das Basis-Volume zurück, das den reservierten Kapazitätszugriff ausgelöst hat.


|===
====
. Klicken Sie auf *Speichern*, um Ihre Änderungen anzuwenden.


.Ergebnis
System Manager ändert die Einstellungen für die reservierte Kapazität des Mitglieds-Volumes sowie die Einstellungen für die reservierte Kapazität aller Mitglied-Volumes in der Konsistenzgruppe.
