---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: pool, creation, initiated, automatically, system, manager, detect, unassigned, drives, storage, array, configure, add, existing 
summary: Die Erstellung des Pools wird automatisch initiiert, wenn System Manager nicht zugewiesene Laufwerke im Speicher-Array erkennt. Mithilfe der automatischen Pool-Erstellung können alle nicht zugewiesenen Laufwerke im Speicher-Array in einem Pool konfiguriert und Laufwerke zu vorhandenen Pools hinzugefügt werden. 
---
= Pool automatisch erstellen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Erstellung des Pools wird automatisch initiiert, wenn System Manager nicht zugewiesene Laufwerke im Speicher-Array erkennt. Mithilfe der automatischen Pool-Erstellung können alle nicht zugewiesenen Laufwerke im Speicher-Array in einem Pool konfiguriert und Laufwerke zu vorhandenen Pools hinzugefügt werden.

.Bevor Sie beginnen
Sie können das Dialogfeld *Pool Auto-Configuration* öffnen, wenn eine der folgenden Bedingungen zutrifft:

* Es wurde mindestens ein nicht zugewiesenes Laufwerk erkannt, das einem vorhandenen Pool mit ähnlichen Laufwerktypen hinzugefügt werden kann.
* Es wurden elf (11) oder mehr nicht zugewiesene Laufwerke erkannt, die zur Erstellung eines neuen Pools verwendet werden können (wenn sie aufgrund unterschiedlicher Antriebstypen nicht zu einem vorhandenen Pool hinzugefügt werden können).


.Über diese Aufgabe
Beachten Sie Folgendes:

* Wenn Sie einem Speicher-Array Laufwerke hinzufügen, erkennt System Manager automatisch die Laufwerke und fordert Sie auf, basierend auf dem Laufwerkstyp und der aktuellen Konfiguration einen einzelnen Pool oder mehrere Pools zu erstellen.
* Wenn bereits Pools definiert wurden, fordert Sie System Manager automatisch auf, die kompatiblen Laufwerke einem vorhandenen Pool hinzuzufügen. Wenn zu einem vorhandenen Pool neue Laufwerke hinzugefügt werden, verteilt System Manager die Daten automatisch auf die neue Kapazität, die jetzt die neuen Laufwerke enthält, die Sie hinzugefügt haben.
* Stellen Sie beim Konfigurieren eines EF600 Storage-Arrays sicher, dass jeder Controller in den ersten 12 Steckplätzen und in den letzten 12 Steckplätzen Zugriff auf eine gleiche Anzahl von Laufwerken hat. Mit dieser Konfiguration können die Controller beide PCIe-Busse auf der Laufwerkseite effektiver nutzen. Derzeit ermöglicht System Manager die Laufwerkauswahl unter der Funktion Erweitert, wenn eine Volume-Gruppe erstellt wird. Für die Erstellung von Pools wird empfohlen, alle Laufwerke im Speicher-Array zu verwenden.


Sie können das Dialogfeld *Pool Auto-Configuration* mit einer der folgenden Methoden starten:

* Wenn nicht zugewiesene Kapazität erkannt wird, wird die Empfehlung für die automatische Konfiguration des Pools auf der Startseite im Bereich Benachrichtigungen angezeigt. Klicken Sie auf *Pool automatisch konfigurieren*, um das Dialogfeld zu starten.
* Sie können das Dialogfeld *Pool Auto-Configuration* auch von der Seite Pools und Volume Groups aus starten, wie in der folgenden Aufgabe beschrieben.


.Schritte
. Wählen Sie Menü:Speicher[Pools & Volume Groups].
. Wählen Sie MENU:Mehr[Pool Auto-Configuration starten].
+
In der Ergebnistabelle werden neue Pools, vorhandene Pools mit hinzugefügten Laufwerken oder beides aufgeführt. Ein neuer Pool wird standardmäßig mit einer sequenziellen Nummer benannt.

+
Beachten Sie, dass System Manager folgende Schritte ausführen wird:

+
** Erstellen Sie einen einzelnen Pool, wenn eine ausreichende Anzahl von Laufwerken mit demselben Laufwerkstyp (HDD oder SSD) und ähnliche Kapazität vorhanden sind.
** Erstellen Sie mehrere Pools, wenn die nicht zugewiesene Kapazität aus verschiedenen Laufwerkstypen besteht.
** Fügen Sie die Laufwerke einem vorhandenen Pool hinzu, wenn bereits ein Pool im Speicher-Array definiert ist, und Sie fügen dem Pool neue Laufwerke desselben Laufwerkstyps hinzu.
** Fügen Sie die Laufwerke desselben Laufwerkstyps zum vorhandenen Pool hinzu. Erstellen Sie dann mithilfe der anderen Laufwerktypen verschiedene Pools, wenn die neuen Laufwerke unterschiedliche Laufwerkstypen haben.


. Um den Namen eines neuen Pools zu ändern, klicken Sie auf das Symbol *Bearbeiten* (der Stift).
. Um zusätzliche Merkmale des Pools anzuzeigen, positionieren Sie den Cursor über oder berühren Sie das Symbol *Details* (die Seite).
+
Es werden Informationen zum Laufwerkstyp, zur Sicherheitsfunktion, zur Data Assurance (da)-Funktion, zum Schutz vor Shelf-Verlust und zum Schutz vor Schubladenverlust angezeigt.

. Klicken Sie Auf *Akzeptieren*.

