---
permalink: sm-storage/create-workloads.html 
sidebar: sidebar 
keywords: create, workloads, type, application, storage, object, support, define, instance, system, manager 
summary: Sie können Workloads für jeden Applikationstyp erstellen. 
---
= Workloads erstellen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Workloads für jeden Applikationstyp erstellen.

.Über diese Aufgabe
Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren. Bei einigen Applikationen konfiguriert System Manager den Workload so, dass er Volumes mit ähnlichen zugrunde liegenden Volume-Merkmalen enthält. Diese Volume-Merkmale werden basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Wenn Sie beispielsweise einen Workload erstellen, der eine Microsoft SQL Server Applikation unterstützt und anschließend Volumes für diesen Workload erstellt, werden die zugrunde liegenden Volume-Merkmale zur Unterstützung von Microsoft SQL Server optimiert.

System Manager empfiehlt nur für die folgenden Applikationstypen eine optimierte Volume-Konfiguration:

* Microsoft® SQL Server™
* Microsoft® Exchange Server™
* Videoüberwachung
* VMware ESXi ™ (für Volumes, die mit dem File System der Virtual Machine verwendet werden sollen)


Beachten Sie folgende Richtlinien:

* _Bei Verwendung eines applikationsspezifischen Workloads_ empfiehlt das System eine optimierte Volume-Konfiguration, um Konflikte zwischen Applikations-Workload-I/O und anderem Datenverkehr aus Ihrer Applikationsinstanz zu minimieren. Sie können die empfohlene Volume-Konfiguration überprüfen und dann die vom System empfohlenen Volumes und Eigenschaften bearbeiten, hinzufügen oder löschen. Verwenden Sie dazu das Dialogfeld *Volumes hinzufügen/bearbeiten*.
* _Bei Verwendung anderer Anwendungstypen_ legen Sie die Volume-Konfiguration manuell über das Dialogfeld *Volumes hinzufügen/bearbeiten* fest.


.Schritte
. Wählen Sie Menü:Storage[Volumes].
. Wählen Sie Menü:Erstellen[Workload].
+
Das Dialogfeld * Anwendungsauslastung erstellen* wird angezeigt.

. Wählen Sie in der Dropdown-Liste den Applikationstyp aus, für den der Workload erstellt werden soll, und geben Sie dann einen Workload-Namen ein.
. Klicken Sie Auf *Erstellen*.


.Nachdem Sie fertig sind
Sie können dem erstellten Workload Storage-Kapazität hinzufügen. Verwenden Sie die Option *Create Volume*, um ein oder mehrere Volumes für eine Anwendung zu erstellen und jedem Volume bestimmte Mengen an Kapazität zuzuweisen.
