---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: create, volumes, using, either, pool, group, selection, depend, primarily, key, storage, requirements, expect, workload, performance, data, protection 
summary: Sie können Volumes entweder mit einem Pool oder einer Volume-Gruppe erstellen. Die beste Auswahl hängt in erster Linie von den wichtigsten Storage-Anforderungen wie dem erwarteten I/O-Workload, den Performance-Anforderungen und den Datensicherungsanforderungen ab. 
---
= Entscheiden Sie, ob ein Pool oder eine Volume-Gruppe verwendet werden soll
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes entweder mit einem Pool oder einer Volume-Gruppe erstellen. Die beste Auswahl hängt in erster Linie von den wichtigsten Storage-Anforderungen wie dem erwarteten I/O-Workload, den Performance-Anforderungen und den Datensicherungsanforderungen ab.



== Gründe für die Auswahl eines Pools oder einer Volume-Gruppe

*Wählen Sie einen Pool*

* Wenn Sie schnellere Laufwerk-Rebuilds und eine vereinfachte Storage-Administration benötigen, benötigen Sie Thin Volumes und/oder einen hochzufälligen Workload.
* Wenn Sie die Daten für jedes Volume zufällig über einen Satz von Laufwerken verteilen möchten, die diesen Pool bilden.
+
Sie können den RAID-Level von Pools oder Volumes in den Pools nicht festlegen oder ändern. Pools verwenden RAID Level 6.



*Wählen Sie eine Volume-Gruppe*

* Wenn Sie die maximale Netzwerkbandbreite des Systems benötigen, die Möglichkeit zur Anpassung von Storage-Einstellungen und einen stark sequenziellen Workload benötigen.
* Wenn Sie die Daten basierend auf RAID-Level über die Laufwerke verteilen möchten. Sie können den RAID-Level beim Erstellen der Volume-Gruppe angeben.
* Wenn Sie die Daten für jedes Volume sequenziell über die Laufwerke schreiben möchten, die die Volume-Gruppe umfassen.


[NOTE]
====
Da Pools mit Volume-Gruppen nebeneinander bestehen können, kann ein Storage-Array sowohl Pools als auch Volume-Gruppen enthalten.

====


== Funktionsunterschiede zwischen Pools und Volume-Gruppen

Die folgende Tabelle bietet einen Funktionsvergleich zwischen Volume-Gruppen und Pools.

[cols="3*"]
|===
| Nutzung | Pool | Volume-Gruppe 


 a| 
Zufälliger Workload
 a| 
Besser
 a| 
Gut



 a| 
Sequenzieller Workload
 a| 
Gut
 a| 
Besser



 a| 
Laufwerks-Rebuild-Zeit
 a| 
Schneller
 a| 
Langsamer



 a| 
Performance (optimaler Modus)
 a| 
Gut: Am besten für kleine Blöcke, zufällige Workloads.
 a| 
Gut: Ideal für große Blöcke, sequenzielle Workloads



 a| 
Performance (Laufwerks-Rebuild-Modus)
 a| 
Besser: In der Regel besser als RAID 6
 a| 
Verschlechtert: Bis zu 40 % Leistungsrückgang



 a| 
Mehrere Laufwerke ausfallen
 a| 
Höhere Datensicherung: Schnellere, priorisierte Rebuilds
 a| 
Weniger Datensicherung: Langsame Rebuilds, höheres Risiko von Datenverlust



 a| 
Hinzufügen von Laufwerken
 a| 
Schneller: Bei laufendem Betrieb in den Pool aufnehmen
 a| 
Langsamer: Erfordert dynamische Kapazitätserweiterung



 a| 
Thin Volumes-Unterstützung
 a| 
Ja.
 a| 
Nein



 a| 
Unterstützung von Solid State Disk (SSD
 a| 
Ja.
 a| 
Ja.



 a| 
Vereinfachte Administration
 a| 
Ja: Keine Hot Spares oder RAID-Einstellungen zu konfigurieren
 a| 
Nein: Wir müssen Hot Spares zuweisen, RAID konfigurieren



 a| 
Abstimmbare Performance
 a| 
Nein
 a| 
Ja.

|===