---
permalink: sm-storage/how-does-my-selected-workload-impact-volume-creation.html 
sidebar: sidebar 
keywords: workload, storage, object, support, application, define, more, instance, system, manager, configure, contain, volumes, similar, underlying, characteristics, optimized, based, type, support, example, create, server, subsequently, underlying 
summary: Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren. Bei einigen Applikationen konfiguriert System Manager den Workload so, dass er Volumes mit ähnlichen zugrunde liegenden Volume-Merkmalen enthält. Diese Volume-Merkmale werden basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Wenn Sie beispielsweise einen Workload erstellen, der eine Microsoft SQL Server Applikation unterstützt und anschließend Volumes für diesen Workload erstellt, werden die zugrunde liegenden Volume-Merkmale zur Unterstützung von Microsoft SQL Server optimiert. 
---
= Wie wirkt sich mein ausgewählter Workload auf die Erstellung des Volumes aus?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren. Bei einigen Applikationen konfiguriert System Manager den Workload so, dass er Volumes mit ähnlichen zugrunde liegenden Volume-Merkmalen enthält. Diese Volume-Merkmale werden basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Wenn Sie beispielsweise einen Workload erstellen, der eine Microsoft SQL Server Applikation unterstützt und anschließend Volumes für diesen Workload erstellt, werden die zugrunde liegenden Volume-Merkmale zur Unterstützung von Microsoft SQL Server optimiert.

* *Anwendungsspezifisch*. Wenn Sie Volumes mit einem applikationsspezifischen Workload erstellen, empfiehlt das System möglicherweise eine optimierte Volume-Konfiguration, um Konflikte zwischen Applikations-Workload-I/O und anderem Datenverkehr aus Ihrer Applikationsinstanz zu minimieren. Volume-Merkmale wie I/O-Typ, Segmentgröße, Controller-Besitz und Lese- und Schreib-Cache werden automatisch für Workloads empfohlen und optimiert, die für die folgenden Applikationstypen erstellt wurden.
+
** Microsoft® SQL Server™
** Microsoft® Exchange Server™
** Videoüberwachungsapplikationen
** VMware ESXi ™ (für Volumes, die mit dem Virtual Machine File System verwendet werden sollen) Sie können die empfohlene Volume-Konfiguration überprüfen und die vom System empfohlenen Volumes und Eigenschaften über das Dialogfeld *Add/Edit Volumes* bearbeiten, hinzufügen oder löschen.


* *Andere* (oder Anwendungen ohne spezifische Unterstützung für die Erstellung von Volumes). Bei anderen Workloads wird eine Volume-Konfiguration verwendet, die manuell angegeben werden muss, wann ein Workload erstellt werden soll, der nicht mit einer bestimmten Applikation verknüpft ist, oder ob System Manager nicht über integrierte Optimierungen für die Applikation verfügt, die Sie im Storage-Array verwenden möchten. Sie müssen die Volume-Konfiguration manuell über das Dialogfeld *Volumes hinzufügen/bearbeiten* festlegen.

