---
permalink: sm-storage/what-is-optimization-capacity-volume-groups.html 
sidebar: sidebar 
keywords: drives, long, life, better, maximum, write, performance, portion, capacity, unallocated 
summary: SSD-Laufwerke haben eine längere Lebensdauer und eine bessere maximale Schreib-Performance, wenn ein Teil ihrer Kapazität nicht zugewiesen ist. 
---
= Was ist die Optimierungskapazität für Volume-Gruppen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD-Laufwerke haben eine längere Lebensdauer und eine bessere maximale Schreib-Performance, wenn ein Teil ihrer Kapazität nicht zugewiesen ist.

Bei Laufwerken, die einer Volume-Gruppe zugeordnet sind, besteht nicht zugewiesene Kapazität aus der freien Kapazität einer Volume-Gruppe (nicht von Volumes genutzte Kapazität) und einem Teil der nutzbaren Kapazität, die als Optimierungskapazität zur Verfügung steht. Die zusätzliche Optimierungskapazität stellt ein Mindestmaß an Optimierungskapazität zur Verfügung, indem die nutzbare Kapazität reduziert wird. Somit ist für die Volume-Erstellung nicht verfügbar.

Wenn eine Volume-Gruppe erstellt wird, wird eine empfohlene Optimierungskapazität generiert, die einen Ausgleich zwischen Performance, Laufwerkverschleiß und verfügbarer Kapazität bietet. Der Schieberegler zusätzliche Optimierung der Kapazität im Dialogfeld *Volume-Gruppeneinstellungen* ermöglicht die Anpassung der Optimierungskapazität einer Volume-Gruppe. Durch das Anpassen des Schiebereglers erhalten Sie eine bessere Performance und längere Lebensdauer der Laufwerke, und zwar auf Kosten der verfügbaren Kapazität oder zusätzlicher verfügbarer Kapazität, und zwar auf Kosten der Leistung und des Verschleißes der Laufwerke.

[NOTE]
====
Der Schieberegler „zusätzliche Optimierung der Kapazität“ ist nur für EF600 Storage-Systeme verfügbar.

====