---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: default, cluster, system, defined, entity, allow, unassociated, host, bus, adapter, port, identifier, logged, storage, array, gain, access, volumes, assign, physically, installed, particular 
summary: 'Das Standard-Cluster ist eine systemdefinierte Einheit, die jedem nicht zugeordneten Host Bus Adapter (HBA)-Host-Port-Identifier, der beim Speicher-Array angemeldet ist, den Zugriff auf alle Volumes ermöglicht, die dem Standardcluster zugewiesen sind. Eine nicht zugeordnete Host-Port-ID ist ein Host-Port, der zwar physisch in einem Host installiert und im Speicher-Array angemeldet ist, nicht logisch mit einem bestimmten Host verknüpft ist.' 
---
= Was ist das Standard-Cluster?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Standard-Cluster ist eine systemdefinierte Einheit, die jedem nicht zugeordneten Host Bus Adapter (HBA)-Host-Port-Identifier, der beim Speicher-Array angemeldet ist, den Zugriff auf alle Volumes ermöglicht, die dem Standardcluster zugewiesen sind. Eine nicht zugeordnete Host-Port-ID ist ein Host-Port, der zwar physisch in einem Host installiert und im Speicher-Array angemeldet ist, nicht logisch mit einem bestimmten Host verknüpft ist.

[NOTE]
====
Wenn Ihre Hosts spezifischen Zugriff auf bestimmte Volumes im Storage-Array haben sollen, müssen Sie das Standardcluster _Not_ verwenden. Stattdessen müssen Sie die Host-Port-IDs den entsprechenden Hosts zuordnen. Dies kann entweder manuell mit System Manager während des Vorgangs „Create Host“ oder automatisch mit dem Host Context Agent (HCA) durchgeführt werden, der auf jedem Host installiert ist. Anschließend weisen Sie Volumes einem einzelnen Host oder einem Host-Cluster zu.

====
Sie sollten das Standard-Cluster in besonderen Situationen verwenden, in denen Ihre externe Speicherumgebung geeignet ist, allen Hosts und allen angemeldeten Host-Port-IDs, die mit dem Speicher-Array verbunden sind, Zugriff auf alle Volumes zu gewähren (All-Access-Modus). Ohne die Hosts dem Storage-Array oder dem System Manager bekannt zu machen.

Zunächst können Sie Volumes über die Befehlszeilenschnittstelle (CLI) nur dem Standard-Cluster zuweisen. Nachdem Sie jedoch dem Standard-Cluster mindestens ein Volume zugewiesen haben, wird diese Einheit (als Standard-Cluster bezeichnet) in System Manager angezeigt und Sie können diese Einheit über System Manager verwalten.
