---
permalink: sm-storage/why-cant-i-increase-my-preservation-capacity.html 
sidebar: sidebar 
keywords: create, volumes, available, usable, capacity, might, able, increase, preservation, capacity 
summary: Wenn Sie Volumes auf allen verfügbaren nutzbaren Kapazitäten erstellt haben, können Sie die dauerhafte Kapazität möglicherweise nicht erhöhen. 
---
= Warum kann ich meine Erhaltungskapazität nicht erhöhen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Volumes auf allen verfügbaren nutzbaren Kapazitäten erstellt haben, können Sie die dauerhafte Kapazität möglicherweise nicht erhöhen.

Bei der Festplattenkapazität wird die in einem Pool reservierte Kapazität zur Unterstützung potenzieller Laufwerksausfälle angegeben. Wenn ein Pool erstellt wird, reserviert System Manager automatisch eine standardmäßige Aufbewahrungskapazität, abhängig von der Anzahl der Laufwerke im Pool. Falls Sie Volumes auf allen verfügbaren nutzbaren Kapazitäten erstellt haben, können Sie die dauerhafte Kapazität auch nicht vergrößern, wenn Sie die Kapazität zum Pool erweitern, indem Sie Laufwerke hinzufügen oder Volumes löschen.

Sie können die Erhaltungskapazität ändern, indem Sie *Speicherung* und dann die Kachel *Pools & Volume Groups* auswählen. Wählen Sie den Pool aus, den Sie bearbeiten möchten. Klicken Sie auf *Einstellungen anzeigen/bearbeiten* und wählen Sie dann die Registerkarte *Einstellungen*.

[NOTE]
====
Die dauerhafte Kapazität wird als eine Reihe von Laufwerken festgelegt, auch wenn die tatsächliche Festplattenkapazität auf den Laufwerken im Pool verteilt ist.

====