---
permalink: sm-mirroring/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirror, percentage, system manager, nearing, full, reserved capacity 
summary: Sie können die Einstellungen für ein gespiegeltes Paar-Volume ändern, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paar-Volumes voll ist. 
---
= Ändern Sie die Einstellungen für die reservierte Kapazität eines gespiegelten Paar-Volumes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für ein gespiegeltes Paar-Volume ändern, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paar-Volumes voll ist.

.Schritte
. Wählen Sie *menu:Speicher[Pools & Volume Groups]*.
. Wählen Sie die Registerkarte *reservierte Kapazität* aus.
. Wählen Sie das zu bearbeitende gespiegelte Paar-Volume aus und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld *Mirrored Pair Volume Reserved Capacity Settings* wird angezeigt.

. Ändern Sie gegebenenfalls die Einstellungen für die reservierte Kapazität des gespiegelten Paar-Volumes.
+
.Felddetails
[%collapsible]
====
[cols="1a,3a"]
|===
| Einstellung | Beschreibung 


 a| 
Benachrichtigen, wenn...
 a| 
Verwenden Sie das Spinner-Feld, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paares sich der vollen Kapazität nähert.

Wenn die reservierte Kapazität für das gespiegelte Paar den angegebenen Schwellenwert überschreitet, sendet System Manager eine Warnmeldung, sodass Sie die reservierte Kapazität erweitern können.


NOTE: Durch Ändern der Alarmeinstellung für ein gespiegeltes Paar wird die Alarmeinstellung für alle gespiegelten Paare, die zur gleichen SpiegelungsConsistency Group gehören, geändert.

|===
====
. Klicken Sie auf *Speichern*, um Ihre Änderungen anzuwenden.

