---
permalink: sm-mirroring/change-role-between-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: perform, role, two, volumes, mirror, participation, synchronous, administration, event, disaster, local, storage, array 
summary: Sie können eine Rollenumkehr zwischen den beiden Volumes in einem gespiegelten Paar, das an der synchronen Spiegelung beteiligt ist, durchführen. Sie ändern die Rolle zwischen den Volumes in einem gespiegelten Paar für administrative Zwecke oder im Falle einer Störung im lokalen Storage-Array. 
---
= Ändern Sie die Rolle zwischen Volumes in einem gespiegelten Paar
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Rollenumkehr zwischen den beiden Volumes in einem gespiegelten Paar, das an der synchronen Spiegelung beteiligt ist, durchführen. Sie ändern die Rolle zwischen den Volumes in einem gespiegelten Paar für administrative Zwecke oder im Falle einer Störung im lokalen Storage-Array.

.Über diese Aufgabe
Sie können das primäre Volume entweder auf die sekundäre Rolle zurückstufen oder das sekundäre Volume zur primären Rolle heraufstufen. Alle Hosts, die auf das primäre Volume zugreifen, haben Lese-/Schreibzugriff auf das Volume. Wenn das primäre Volume zum sekundären Volume wird, werden nur durch den primären Controller initiierte Remote-Schreibvorgänge auf das Volume geschrieben.

.Schritte
. Wählen Sie *menu:Speicherung[Synchronous Mirroring]*.
. Wählen Sie das gespiegelte Paar aus, das die Volumes enthält, für die Sie die Rolle ändern möchten, und wählen Sie dann *menu:Mehr[Rolle ändern].*
+
Das System zeigt eine Bestätigung an.

. Bestätigen Sie, dass Sie die Rolle der Volumes ändern möchten, und wählen Sie dann *Rolle ändern*.
+
[NOTE]
====
Wenn das lokale Speicher-Array nicht mit dem Remote-Speicher-Array kommunizieren kann, zeigt das System das Dialogfeld *Storage Array nicht ansprechbar* an, wenn eine Rollenänderung angefordert wird, aber das Remote-Speicher-Array kann nicht kontaktiert werden. Klicken Sie auf *Ja*, um die Rollenänderung zu erzwingen.

====


.Ergebnisse
System Manager führt die folgende Aktion durch:

* Wenn das zugehörige Volume im gespiegelten Paar kontaktiert werden kann, ändern sich die Rollen zwischen den Volumes. System Manager befördert das sekundäre Volume im gespiegelten Paar in die primäre Rolle oder deprisiert das primäre Volume im gespiegelten Paar auf die sekundäre Rolle (je nach Auswahl).

