---
permalink: sm-mirroring/deactivate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: deactivate, synchronous, mirror, storage, array, re-establish, normal, ports, storage, array 
summary: 'Sie können die Funktion Synchronous Mirroring auf einem Speicher-Array deaktivieren, um die normale Nutzung des Host Bus Adapters (HBA) Host-Ports 4, der für die Datenübertragung an der Spiegelung reserviert war, wiederherzustellen.' 
---
= Deaktivieren Sie die synchrone Spiegelung
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Funktion Synchronous Mirroring auf einem Speicher-Array deaktivieren, um die normale Nutzung des Host Bus Adapters (HBA) Host-Ports 4, der für die Datenübertragung an der Spiegelung reserviert war, wiederherzustellen.

Sie müssen alle synchronen Spiegelbeziehungen gelöscht haben. Überprüfen Sie, ob alle gespiegelten Paare aus dem Speicher-Array gelöscht wurden.

.Schritte
. Wählen Sie *menu:Speicherung[Synchronous Mirroring]*.
. Wählen Sie *menu:Sonstige Aufgaben[Deaktivieren]*.
+
Das System zeigt eine Bestätigung an.

. Wählen Sie zur Bestätigung * Ja* aus.


.Ergebnisse
* Der HBA-Host-Port 4 des Controllers, der für die Kommunikation mit synchroner Spiegelung vorgesehen war, kann jetzt Lese- und Schreibanfragen des Hosts akzeptieren.
* Die Volumes mit reservierter Kapazität im Speicher-Array werden gelöscht.

