---
permalink: sm-mirroring/delete-mirror-consistency-group.html 
sidebar: sidebar 
keywords: delete, mirror, consistency, group, local, storage 
summary: Sie können gespiegelte Konsistenzgruppen löschen, die nicht mehr im lokalen Storage Array und im Remote-Storage Array benötigt werden. 
---
= Löschen der gespiegelten Konsistenzgruppe
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können gespiegelte Konsistenzgruppen löschen, die nicht mehr im lokalen Storage Array und im Remote-Storage Array benötigt werden.

.Bevor Sie beginnen
Alle gespiegelten Paare müssen aus der Consistency Mirror-Gruppe entfernt werden.

.Schritte
. Wählen Sie *menu:Storage[Asynchronous Mirroring]*.
. Wählen Sie die Registerkarte * Consistency Groups spiegeln* aus.
+
Die Tabelle Mirror Consistency Group wird angezeigt und zeigt alle dem Speicher-Array zugeordneten Spiegelkonsistency Groups an.

. Wählen Sie die zu löschende Spiegelkonsistent-Gruppe aus, und wählen Sie dann *menu:Sonstige Aufgaben[Löschen]* aus.
+
Das System zeigt eine Bestätigung an.

. Wählen Sie *Ja* aus, um die Consistency Mirror-Gruppe zu löschen.


.Ergebnisse
System Manager führt die folgenden Aktionen durch:

* Löscht zuerst die SpiegelConsistency Group auf dem lokalen Speicher-Array und löscht dann die SpiegelConsistency Group auf dem Remote-Speicher-Array.
* Entfernt die gespiegelte Konsistenzgruppe aus der Tabelle „Konsistenzgruppe spiegeln“.


.Nachdem Sie fertig sind
Gelegentlich kann es vorkommen, dass die gespiegelte Konsistenzgruppe erfolgreich aus dem lokalen Speicher-Array gelöscht wird, aber ein Kommunikationsfehler verhindert, dass die gespiegelte Konsistenzgruppe aus dem Remote-Speicher-Array gelöscht wird. In diesem Fall müssen Sie auf das Remote-Speicher-Array zugreifen, um die entsprechende gespiegelte Konsistenzgruppe zu löschen.
