---
permalink: sm-mirroring/re-synchronize-mirror-consistency-group-manually.html 
sidebar: sidebar 
keywords: manual, mirror, pair, consistency, group 
summary: Sie können die Neusynchronisierung für alle gespiegelten Paare innerhalb einer SpiegelungsConsistency Group manuell starten. 
---
= Die SpiegelungsConsistency Group manuell neu synchronisieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Neusynchronisierung für alle gespiegelten Paare innerhalb einer SpiegelungsConsistency Group manuell starten.

.Schritte
. Wählen Sie *menu:Speicherung[Synchronous Mirroring]*.
. Wählen Sie die Registerkarte * Consistency Groups spiegeln* aus.
+
Die Tabelle Mirror Consistency Group wird angezeigt und zeigt alle dem Speicher-Array zugeordneten Spiegelkonsistency Groups an.

. Wählen Sie die SpiegelungsConsistency Group aus, die Sie erneut synchronisieren möchten, und wählen Sie dann *menu:Mehr[manuell neu synchronisieren]* aus.
+
Das System zeigt eine Bestätigung an.

. Wählen Sie zur Bestätigung * Ja* aus.


.Ergebnisse
Das System führt die folgenden Aktionen durch:

* Initiiert die erneute Synchronisation von Daten auf allen gespiegelten Paaren innerhalb der ausgewählten SpiegelungsConsistency Group.
* Aktualisiert geänderte Daten vom lokalen Speicher-Array auf das Remote-Speicher-Array.

