---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: Sie müssen das Speicher-Array mit einem Administratorkennwort konfigurieren, um es vor unbefugtem Zugriff zu schützen. 
---
= Schutz von Administratorpasswörtern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das Speicher-Array mit einem Administratorkennwort konfigurieren, um es vor unbefugtem Zugriff zu schützen.



== Festlegen eines Administratorpassworts

Das Einrichten eines Administratorpassworts für Ihr Storage Array schützt es vor Benutzern, die unwissentlich oder böswillig destruktive Befehle ausführen. Sie müssen ein Administratorkennwort festlegen, wenn Sie System Manager zum ersten Mal starten.

Es gibt ein Administratorpasswort, das von allen Benutzern freigegeben wird. Jeder Benutzer mit diesem Kennwort kann Konfigurationsänderungen am Speicher-Array vornehmen, z. B. Objekte oder Einstellungen hinzufügen, ändern oder entfernen.



== Geben Sie Ihr Kennwort ein

Das System fordert Sie zur Eingabe des Passworts nur einmal während einer einzigen Verwaltungssitzung auf. Eine Sitzung läuft nach 20 Minuten Inaktivität ab. Zu diesem Zeitpunkt müssen Sie das Passwort erneut eingeben.

Wenn ein anderer Benutzer, der dasselbe Speicher-Array von einem anderen Management-Client aus verwaltet, das Passwort während der Sitzung ändert, werden Sie beim nächsten Versuch eines Konfigurationsvorgangs oder einer Ansicht aufgefordert, ein Passwort einzugeben.

Aus Sicherheitsgründen können Sie nur fünf Mal versuchen, ein Passwort einzugeben, bevor das Speicherarray den Status „Sperre“ eingibt. In diesem Zustand weist das Speicherarray nachfolgende Passwortversuche zurück. Sie müssen 10 Minuten warten, bis das Speicherarray auf einen „normalen“ Zustand zurückgesetzt wird, bevor Sie erneut versuchen, ein Passwort einzugeben.



== Entfernen von Laufwerken mit Kennwortschutz

Das Passwort wird auf einem reservierten Bereich jedes Laufwerks im Speicher-Array gespeichert. Wenn Sie alle Laufwerke aus einem Speicher-Array entfernen, funktioniert das Kennwort nicht mehr. Um diese Bedingung zu beheben, installieren Sie eines der Originallaufwerke erneut in das Speicher-Array.



== Passwortschutz wird entfernt

Wenn Sie keine Befehle mehr kennwortgeschützt haben möchten, geben Sie das aktuelle Administratorpasswort ein, und lassen Sie die neuen Textfelder für das Kennwort leer.

[NOTE]
====
Wenn Konfigurationsbefehle auf einem Storage-Array ausgeführt werden, kann dies zu ernsthaften Schäden und Datenverlusten führen. Aus diesem Grund sollten Sie immer ein Administratorkennwort für Ihr Speicherarray festlegen. Verwenden Sie ein langes Administratorkennwort mit mindestens 15 alphanumerischen Zeichen, um die Sicherheit zu erhöhen.

====