---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: insert, lock, nvme, storage array, key file, psid, security key, drive data 
summary: 'Wenn Sie ein oder mehrere gesperrte NVMe-Laufwerke in ein Storage-Array einfügen, können Sie die Laufwerkdaten entsperren, indem Sie die der Laufwerke zugeordnete Sicherheitsschlüsseldatei hinzufügen. Wenn Sie keinen Sicherheitsschlüssel haben, können Sie auf jedem gesperrten NVMe-Laufwerk einen Reset durchführen, indem Sie seine physische Sicherheits-ID (PSID) eingeben, um seine Sicherheitsattribute zurückzusetzen und die Laufwerkdaten zu löschen.' 
---
= Gesperrte NVMe-Laufwerke entsperren oder zurücksetzen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein oder mehrere gesperrte NVMe-Laufwerke in ein Storage-Array einfügen, können Sie die Laufwerkdaten entsperren, indem Sie die der Laufwerke zugeordnete Sicherheitsschlüsseldatei hinzufügen. Wenn Sie keinen Sicherheitsschlüssel haben, können Sie auf jedem gesperrten NVMe-Laufwerk einen Reset durchführen, indem Sie seine physische Sicherheits-ID (PSID) eingeben, um seine Sicherheitsattribute zurückzusetzen und die Laufwerkdaten zu löschen.

.Bevor Sie beginnen
* Stellen Sie bei der Option Entsperren sicher, dass die Sicherheitsschlüsseldatei (mit einer Erweiterung von) verwendet wird `.slk`) Ist auf dem Management-Client verfügbar (das System mit einem Browser, der für den Zugriff auf System Manager verwendet wird). Sie müssen auch die Passphrase kennen, die mit der Taste verbunden ist.
* Für die Option Zurücksetzen müssen Sie die PSID auf jedem Laufwerk finden, das Sie zurücksetzen möchten. Um die PSID zu finden, entfernen Sie das Laufwerk physisch und suchen Sie die PSID-Zeichenfolge (maximal 32 Zeichen) auf dem Laufwerketikett, und installieren Sie dann das Laufwerk neu.


.Über diese Aufgabe
In dieser Aufgabe wird beschrieben, wie Daten auf NVMe-Laufwerken durch den Import einer Sicherheitsschlüsseldatei in das Storage-Array entsperrt werden. In Fällen, in denen der Sicherheitsschlüssel nicht verfügbar ist, beschreibt diese Aufgabe auch, wie ein Reset auf einem gesperrten Laufwerk durchgeführt wird.

[NOTE]
====
Wenn das Laufwerk über einen externen Schlüsselverwaltungsserver gesperrt wurde, wählen Sie in System Manager *menu:Einstellungen[System > Sicherheitsschlüsselverwaltung]* aus, um die externe Schlüsselverwaltung zu konfigurieren und das Laufwerk zu entsperren.

====
.Schritte
. Wählen Sie *Hardware*.
. Wenn die Grafik die Controller zeigt, klicken Sie auf *Vorderseite des Regals anzeigen*.
+
Die Grafik ändert sich, um die Laufwerke anstelle der Controller anzuzeigen.

. Wählen Sie das NVMe-Laufwerk aus, das Sie entsperren oder zurücksetzen möchten.
+
Das Kontextmenü des Laufwerks wird geöffnet.

. Wählen Sie *Entsperren*, um die Sicherheitsschlüsseldatei anzuwenden, oder *Zurücksetzen*, wenn Sie keine Sicherheitsschlüsseldatei haben.
+
Diese Optionen werden nur angezeigt, wenn Sie ein gesperrtes NVMe-Laufwerk auswählen.

+
[CAUTION]
====
Während eines Reset-Vorgangs werden alle Daten gelöscht. Führen Sie nur einen Reset aus, wenn Sie keinen Sicherheitsschlüssel haben. Beim Zurücksetzen eines gesperrten Laufwerks werden alle Daten auf dem Laufwerk endgültig entfernt und die Sicherheitsattribute auf „sicher-fähig“ zurückgesetzt, aber nicht aktiviert. *Dieser Vorgang ist nicht umkehrbar.*

====
. Führen Sie einen der folgenden Schritte aus:
+
.. *Entsperren*: Klicken Sie im Dialogfeld sicheres Laufwerk entsperren auf *Durchsuchen* und wählen Sie dann die Sicherheitsschlüsseldatei aus, die dem Laufwerk entspricht, das Sie entsperren möchten. Geben Sie dann den Passphrase ein und klicken Sie dann auf *Entsperren*.
.. *Zurücksetzen*: Geben Sie im Dialogfeld Sperrtes Laufwerk zurücksetzen die PSID-Zeichenfolge in das Feld ein, und geben Sie dann ein `RESET` Zur Bestätigung. Klicken Sie Auf *Zurücksetzen*.
+
Für einen Vorgang zum Entsperren muss dieser Vorgang nur einmal ausgeführt werden, um alle NVMe-Laufwerke freizuschalten. Bei einem Reset-Vorgang müssen Sie jedes Laufwerk einzeln auswählen, das Sie zurücksetzen möchten.





.Ergebnisse
Das NVMe-Laufwerk kann nun in einer anderen Volume-Gruppe oder einem anderen Festplatten-Pool oder in einem anderen Storage-Array verwendet werden.
