---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: ten server, snmp traps, sending 
summary: Sie können bis zu 10 Server zum Senden von SNMP-Traps hinzufügen. 
---
= Fügen Sie Trap-Ziele für SNMP-Warnungen hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können bis zu 10 Server zum Senden von SNMP-Traps hinzufügen.

.Bevor Sie beginnen
* Der Netzwerkserver, den Sie hinzufügen möchten, muss mit einer SNMP-Serviceanwendung konfiguriert sein. Sie benötigen die Netzwerkadresse dieses Servers (entweder eine IPv4- oder eine IPv6-Adresse), damit der Ereignismonitor Trap-Meldungen an diese Adresse senden kann. Sie können mehrere Server verwenden (bis zu 10 Server sind zulässig).
* Es muss ein Community-Name erstellt werden, der nur aus druckbaren ASCII-Zeichen besteht. Der Community-Name, ein String, der wie ein Kennwort für die Netzwerkserver fungiert, wird in der Regel von einem Netzwerkadministrator erstellt. Es können bis zu 256 Communities erstellt werden.
* Die Management Information Base (MIB)-Datei wurde kopiert und mit der SNMP-Dienst-Anwendung auf dem Server kompiliert. Diese MIB-Datei definiert die Daten, die überwacht und verwaltet werden.
+
Wenn Sie nicht über die MIB-Datei, können Sie sie von der NetApp Support-Website erhalten:

+
** Gehen Sie zu https://mysupport.netapp.com/site/["NetApp Support"^].
** Klicken Sie Auf *Downloads*.
** Klicken Sie Auf *Software*.
** Suchen Sie Ihre Verwaltungssoftware (z. B. SANtricity-System-Manager), und klicken Sie dann rechts auf *Los!*.
** Klicken Sie auf *Ansicht & Download* auf der neuesten Version.
** Klicken Sie unten auf der Seite auf *Weiter*.
** Akzeptieren Sie die EULA.
** Scrollen Sie nach unten, bis Sie *MIB-Datei für SNMP-Traps* sehen, und klicken Sie dann auf den Link, um die Datei herunterzuladen.




.Schritte
. Wählen Sie *Einstellungen* > *Alarme*.
. Wählen Sie die Registerkarte *SNMP* aus.
+
Die aktuell definierten Trap-Ziele werden in der Tabelle angezeigt.

. Wählen Sie *Trap Desinations Hinzufügen*.
+
Das Dialogfeld Trap-Ziele hinzufügen wird geöffnet.

. Geben Sie ein oder mehrere Trap-Ziele ein, wählen Sie die zugehörigen Community-Namen aus, und klicken Sie dann auf *Hinzufügen*.
+
** *Trap-Ziel* -- Geben Sie eine IPv4- oder IPv6-Adresse des Servers ein, auf dem ein SNMP-Dienst ausgeführt wird.
** *Community-Name* -- Wählen Sie im Dropdown-Menü den Community-Namen für dieses Trap-Ziel aus. (Wenn Sie nur einen Community-Namen definiert haben, wird der Name bereits in diesem Feld angezeigt.)
** *Authentifizierungsfehler senden Trap* -- Wählen Sie diese Option (das Kontrollkästchen) aus, wenn Sie das Trap-Ziel benachrichtigen möchten, wenn eine SNMP-Anfrage aufgrund eines nicht erkannten Community-Namens abgelehnt wird. Nach dem Klicken auf *Hinzufügen* werden die Trap-Ziele und die zugehörigen Community-Namen in der Tabelle angezeigt.


. Um sicherzustellen, dass ein Trap gültig ist, wählen Sie ein Trap-Ziel aus der Tabelle aus, und klicken Sie dann auf *Trap-Ziel testen*, um einen Test-Trap an die konfigurierte Adresse zu senden.


.Ergebnisse
Der Ereignismonitor sendet SNMP-Traps an den/die Server(s), wenn ein alertable Ereignis auftritt.
