---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: view, imported, certificate, information, 
summary: Auf der Seite Zertifikate können Sie den Zertifikatstyp, die ausstellende Behörde und den gültigen Datumsbereich der Zertifikate für das Speicher-Array anzeigen. 
---
= Anzeigen importierter Zertifikatinformationen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Zertifikate können Sie den Zertifikatstyp, die ausstellende Behörde und den gültigen Datumsbereich der Zertifikate für das Speicher-Array anzeigen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden keine Zertifikatfunktionen angezeigt.


.Schritte
. Wählen Sie Menü:Einstellungen[Zertifikate].
. Wählen Sie eine der Registerkarten aus, um Informationen zu den Zertifikaten anzuzeigen.
+
[cols="1a,3a"]
|===
| Registerkarte | Beschreibung 


 a| 
Array-Management
 a| 
Zeigen Sie Informationen zu den für jeden Controller importierten CA-signierten Zertifikaten an, einschließlich der Root-Datei, der Zwischendatei(en) und der Serverdatei(en).



 a| 
Bewährt
 a| 
Informationen über alle anderen Arten von Zertifikaten anzeigen, die für die Controller importiert wurden. Verwenden Sie das Filterfeld unter *Zertifikate anzeigen, die...* sind, um entweder vom Benutzer installierte oder vorinstallierte Zertifikate anzuzeigen.

** *Vom Benutzer installiert*. Zertifikate, die ein Benutzer auf das Speicher-Array hochgeladen hat. Dies kann vertrauenswürdige Zertifikate enthalten, wenn der Controller als Client (anstelle eines Servers), LDAPS-Zertifikate und Identity Federation-Zertifikate fungiert.
** *Vorinstalliert*. Im Speicher-Array enthaltene selbstsignierte Zertifikate.




 a| 
Verschlüsselungs-Management
 a| 
Zeigen Sie Informationen zu den für einen externen Schlüsselverwaltungsserver importierten CA-signierten Zertifikaten an.

|===

