---
permalink: sm-settings/what-else-do-i-need-to-do-to-configure-or-diagnose-nvme-over-roce.html 
sidebar: sidebar 
keywords: configure, manage, nvme, roce, hardware, settings page 
summary: NVMe over RoCE kann über die Seiten für Hardware und Einstellungen konfiguriert und gemanagt werden. 
---
= Was muss ich sonst noch tun, um NVMe over RoCE zu konfigurieren oder zu diagnostizieren?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe over RoCE kann über die Seiten für Hardware und Einstellungen konfiguriert und gemanagt werden.

[NOTE]
====
Die NVMe-over-RoCE-Einstellungen sind nur verfügbar, wenn der Controller des Storage-Arrays einen NVMe-over-RoCE-Port umfasst.

====


== Konfiguration und Diagnose von NVMe over RoCE

[cols="1a,3a"]
|===
| Aktion | Standort 


 a| 
Konfigurieren Sie NVMe over RoCE-Ports
 a| 
. Wählen Sie *Hardware*.
. Wählen Sie *Rückseite des Regals anzeigen*.
. Wählen Sie einen Controller aus.
. Wählen Sie *NVMe over RoCE Ports konfigurieren* aus.


Oder

. Wählen Sie *menu:Einstellungen[System]*.
. Scrollen Sie nach unten zu *NVMe over RoCE settings* und wählen Sie dann *Configure NVMe over RoCE Ports* aus.




 a| 
Anzeigen der NVMe over Fabrics Statistiken
 a| 
. Wählen Sie *menu:Einstellungen[System]*.
. Scrollen Sie nach unten zu *NVMe over RoCE settings* und wählen Sie dann *View NVMe over Fabrics Statistics* aus.


|===