---
permalink: sm-support/dcbx-operational-state-statistics.html 
sidebar: sidebar 
keywords: operational, state, statistics 
summary: Statistiken zum DCBX-Betriebsstatus 
---
= Statistiken zum DCBX-Betriebsstatus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Wenn Sie Data Center Bridging Exchange (DCBX) Operational State Statistics auswählen, werden diese Statistiken angezeigt.

[cols="2*"]
|===
| Statistik | Definition 


 a| 
ISCSI-Host-Port
 a| 
Zeigt die Position des erkannten Host-Ports im Controller #, Port #-Format an.



 a| 
Prioritätsgruppe
 a| 
Gibt den Betriebszustand der Anwendung „Priority Group (PG)“ an. Der Status ist entweder aktiviert oder deaktiviert.



 a| 
Prioritätsbasierte Flusssteuerung
 a| 
Zeigt den Betriebszustand der PFC-Funktion (Priority-Based Flow Control) an. Der Status ist entweder aktiviert oder deaktiviert.



 a| 
ISCSI-Funktion
 a| 
Zeigt den Betriebszustand der iSCSI-Anwendung (Internet Small Computer System Interface) an. Der Status ist entweder aktiviert oder deaktiviert.



 a| 
FCoE-Bandbreite
 a| 
Zeigt den Status der FCoE-Bandbreite (Fibre Channel over Ethernet) an. Der Status lautet wahr oder falsch.



 a| 
Keine Übereinstimmung der FCoE/FIP-Zuordnung stimmt nicht überein
 a| 
Zeigt an, ob eine Zuordnung zwischen FCoE und dem FCoE Initialization Protocol (FIP) nicht stimmt. Der Wert lautet wahr oder falsch.

|===
Weitere Statistiken zum Betriebsstatus von DCBX finden Sie in der Statuserfassungsdatei.
