---
permalink: um-certificates/import-array-certificates-unified.html 
sidebar: sidebar 
keywords: import certificate, strong array, authentication, ca, santricity, unified manager, self signed 
summary: 'Bei Bedarf können Zertifikate für die Speicher-Arrays importiert werden, sodass sie sich mit dem System authentifizieren können, das SANtricity Unified Manager hostet. Zertifikate können von einer Zertifizierungsstelle (CA) signiert oder selbst signiert werden.' 
---
= Importieren Sie Zertifikate für Arrays
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Bedarf können Zertifikate für die Speicher-Arrays importiert werden, sodass sie sich mit dem System authentifizieren können, das SANtricity Unified Manager hostet. Zertifikate können von einer Zertifizierungsstelle (CA) signiert oder selbst signiert werden.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden keine Zertifikatfunktionen angezeigt.
* Wenn Sie vertrauenswürdige Zertifikate importieren, müssen die Zertifikate für die Speicher-Array-Controller mit SANtricity System Manager importiert werden.


.Schritte
. Wählen Sie *Zertifikatverwaltung*.
. Wählen Sie die Registerkarte * Trusted* aus.
+
Auf dieser Seite werden alle Zertifikate angezeigt, die für die Speicher-Arrays gemeldet wurden.

. Wählen Sie entweder *menu:Import[Certificates]*, um ein CA-Zertifikat zu importieren, oder *menu:Import[Self-signierte Speicher-Array-Zertifikate]*, um ein selbstsigniertes Zertifikat zu importieren.
+
Um die Ansicht einzuschränken, können Sie das Filterfeld *Zertifikate anzeigen verwenden, das...* ist, oder Sie können die Zertifikatzeilen sortieren, indem Sie auf eine der Spaltenüberschrift klicken.

. Wählen Sie im Dialogfeld das Zertifikat aus und klicken Sie dann auf *Import*.
+
Das Zertifikat wird hochgeladen und validiert.


