---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: configure, santricity, unified, manager, administrator, password, protect, unauthorized, access 
summary: Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unbefugtem Zugriff zu schützen. 
---
= Schutz von Administratorpasswörtern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unbefugtem Zugriff zu schützen.



== Festlegen eines Administratorpassworts

Das Einrichten eines Administratorpassworts schützt die Software vor Benutzern, die unwissentlich oder böswillig zerstörerische Befehle ausführen. Sie müssen ein Administratorkennwort festlegen, wenn Sie Unified Manager zum ersten Mal starten.

Es gibt ein Administratorpasswort, das von allen Benutzern freigegeben wird. Jeder Benutzer mit diesem Kennwort kann Konfigurationsänderungen an Speichersystemen vornehmen.



== Geben Sie Ihr Kennwort ein

Die Software fordert Sie zur Eingabe des Passworts nur einmal während einer einzigen Verwaltungssitzung auf. Eine Sitzung läuft nach 30 Minuten Inaktivität standardmäßig aus. Zu diesem Zeitpunkt müssen Sie das Passwort erneut eingeben. Sie können die Sitzungszeitüberschreitung bei Bedarf anpassen.

Wenn ein anderer Benutzer von einem anderen Management-Client auf die Software zugreift und das Passwort während der Sitzung ändert, werden Sie beim nächsten Versuch eines Konfigurationsvorgangs oder einer Ansicht aufgefordert, ein Passwort einzugeben.

Aus Sicherheitsgründen können Sie versuchen, ein Passwort nur fünf Mal einzugeben, bevor die Software den Status „Sperre“ eingibt. In diesem Zustand lehnt die Software nachfolgende Passwortversuche ab. Sie müssen 10 Minuten warten, um den Status „Normal“ zurückzusetzen, bevor Sie erneut versuchen, ein Passwort einzugeben.
